### ISSUE TITLE
FR: Push Notifications

### ISSUE THREAD

**Issue by profzelonka** [GreenMeteor/humhub-app#1]
There's the outdated app https://github.com/evolved37/github_android_humhub which uses the old FirebaseInstanceIdService. It's since been replaced with the FirebaseMessagingService, not sure how similar it is so this may be a good reference.

The idea is to implement the firebase messaging service for push notifications. I'm not experienced to know if this guide is all that needs to be done? http://shubhank101.github.io/iOSAndroidChaosOverFlow/2016/06/Implementing-FCM-(-Firebase-Cloud-Messaging-)-in-Android-App This is for Firebase Cloud Messaging not sure if instead it needs to be the FirebaseMessagingService specifically instead?

**Comment by ArchBlood** [comment]
First of all I'd like to say thank you for creating the issue, second I'd like to ask if you've tried using the following module beforehand?
https://github.com/humhub-contrib/fcm-push

**Comment by profzelonka** [comment]
Implementing the required SDK additions from Firebase into the build.gradle files creates errors and forces gradle version updates and other things, got it to build the app but it doesn't even open in itself anymore. How is fcm-push integrated with this android app? The integration is missing.

**Comment by ArchBlood** [comment]
> Implementing the required SDK additions from Firebase into the build.gradle files creates errors and forces gradle version updates and other things, got it to build the app but it doesn't even open in itself anymore. How is fcm-push integrated with this android app? The integration is missing.

The link that I shared is the module that is placed in `/protected/modules` and enabled on your HumHub instance side.

**Comment by ArchBlood** [comment]
As for your other issue when it comes to the implementation part, don't worry I'm currently working on an implementation for TWA.

**Comment by profzelonka** [comment]
Right, but it does nothing without the app implementation else how does it know which mobile device to notify? 
Looking forward to your implementation! I've tried all I know and push notifications just don't happen. (Firebase's cloud notifications do tho, so we know that works off the bat.)

**Comment by marc-farre** [comment]
After installing Firebase on Humhub, mobile notifications are working, but when I click on it (on Android 10), instead of opening the app, it opens another window (a sort of separated window of Chrome), the one on the second screenshot:

![image](https://user-images.githubusercontent.com/23310825/193754723-ea091d92-5da5-4396-8cca-4ecc685ebaa0.png)
![image](https://user-images.githubusercontent.com/23310825/193754751-129cfc03-9396-465a-8219-1121e6457eba.png)

**Comment by ArchBlood** [comment]
Will look into this as soon as I can

**Comment by ArchBlood** [comment]
> After installing Firebase on Humhub, mobile notifications are working, but when I click on it (on Android 12), instead of opening the app, it opens another window (a sort of separated window of Chrome), the one on the second screenshot:
> 
> ![image](https://user-images.githubusercontent.com/23310825/193754723-ea091d92-5da5-4396-8cca-4ecc685ebaa0.png) ![image](https://user-images.githubusercontent.com/23310825/193754751-129cfc03-9396-465a-8219-1121e6457eba.png)

Could you provide which browser and what version?

Also are you using the browser itself or HumHub's native PWA support when testing?

**Comment by marc-farre** [comment]
The browser is Brave 1.44.105, Chromium 106.0.5249.91 on Android 10.

When testing, all apps are closed (or only the app is open, the browser is closed), and I didn't use Humhub's PWA (I mean, if I go on Humhub in the browser and it asks me if I want to add it to the desktop, I don't do it).

The notification is sent with the computer, from another account, by mentioning the account logged in to the app.

**Comment by samuk** [comment]
Is it worth investigating https://supabase.com/docs/guides/functions  as an alternative for push? Many people are keen to de-Google their services for privacy reasons

**Comment by ArchBlood** [comment]
> Is it worth investigating https://supabase.com/docs/guides/functions  as an alternative for push? Many people are keen to de-Google their services for privacy reasons

I plan on using as less JavaScript as possible, I thank you for the suggestion but we will probably continue with our current methods in Java as I'm more familiar with the language than Deno and other JavaScript languages, not to mention that I would have to start from scratch again and it's currently not possible within our or my own time.

**Comment by samuk** [comment]
Thanks that makes sense.

For completeness, I did spot
https://ntfy.sh/
https://github.com/binwiederhier/ntfy

Again it's in Go not Java

**Comment by ArchBlood** [comment]
> Thanks that makes sense.
> 
> For completeness, I did spot https://ntfy.sh/ https://github.com/binwiederhier/ntfy
> 
> Again it's in Go not Java

I would rather stick with Java;

### iOS Options
https://github.com/jchambers/pushy
https://pusher.com/docs/channels/getting_started/ios/
https://documentation.onesignal.com/docs/ios-sdk-setup
https://firebase.google.com/docs/ios/setup

### Android Options
https://pusher.com/docs/channels/getting_started/android/
https://documentation.onesignal.com/docs/android-sdk-setup
https://firebase.google.com/docs/android/setup

> Note: All options are subject to change.

**Comment by profzelonka** [comment]
> After installing Firebase on Humhub, mobile notifications are working

Hey @funkycram could you provide how this was accomplished? Is this on the current release of GreenMeteor's app? Or what was your implementation? 

@ArchBlood were you able to reproduce the success of notifications, and the bug?

Hoping to get this going.

**Comment by ArchBlood** [comment]
> > After installing Firebase on Humhub, mobile notifications are working
> 
> Hey @funkycram could you provide how this was accomplished? Is this on the current release of GreenMeteor's app? Or what was your implementation? 
> 
> @ArchBlood were you able to reproduce the success of notifications, and the bug?
> 
> Hoping to get this going. 

The current situation of the app we were creating serves no purpose anymore as HumHub has published their own `HumHub/app`.

**Comment by profzelonka** [comment]
Thanks man, where have I been!?! Cheers
